---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sample-rabbitmq
  namespace: default
spec:
  selector:
    matchLabels:
      app: sample-rabbitmq
  replicas: 3
  template:
    metadata:
      labels:
        app: sample-rabbitmq
    spec:
      containers:
      - name: sample-rabbitmq
        image: rabbitmq:3.13  # Pin version for reproducibility
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 5672
            name: rmq
        resources:
          requests:
            cpu: "200m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
        securityContext:
          runAsNonRoot: true
          runAsUser: 999  # rabbitmq user
          allowPrivilegeEscalation: false
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
            - ALL
        livenessProbe:
          exec:
            command:
            - rabbitmq-diagnostics
            - ping
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - rabbitmq-diagnostics
            - check_port_connectivity
          initialDelaySeconds: 10
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: sample-rabbitmq
  namespace: default
spec:
  selector:
    app: sample-rabbitmq
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672
---
apiVersion: v1
kind: Service
metadata:
  name: sample-rabbitmq-headless
  namespace: default
spec:
  clusterIP: None
  selector:
    app: sample-rabbitmq
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672
